### ISSUE TITLE
Configuration for behavior on different virtual desktops

### ISSUE THREAD

**Issue by BANOnotIT** [hedgieinsocks/gnome-extension-toggler#2]
Right now when you ask to open terminal it switches to the desktop that terminal was open at. Would be great to have some option to configure this behavior.

Options:
- select desktop with already opened terminal (current, default)
- open new instance of terminal for current virtual desktop
- move already open terminal to current desktop

**Comment by hedgieinsocks** [comment]
Thank you for your suggestion. I'd love to see that implemented. Alas, I don't use workspaces myself and have neither enough time nor gjs knowledge to pull it off anytime soon.

**Comment by BANOnotIT** [comment]
I think I can manage to implement this simple algorithm for multiple workspaces.

But I don't have any experience with gjs at all, and I can't even find API docs that cover the methods you used in this extension. Could you provide the one you used? Also, would be great if you can give any idea of how to debug this thing.

**Comment by BANOnotIT** [comment]
Found an extension with functionality similar to described here.

https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/blob/main/extensions/auto-move-windows/extension.js

**Comment by hedgieinsocks** [comment]
Thank you for your input! I use https://gjs.guide/extensions/development/debugging.html while developing. As for the methods, I either check the source code https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/main/js/ui or take a glimpse from other projects. 

Now, after checking the auto-move-windows source code, I've already managed to implement _move already open terminal to current desktop_ option. And it is obvious that this must become the new default. So it seems that this will come together sometime this week. So, I suggest that I merge your preference PR, and then I'll slap the updated gjs logic.

P.S. 

Initially, I created this extension inspired by an awesome but abandoned extension https://github.com/pcbowers/focus-window

Also, I've just found this feature-rich project https://github.com/diegodario88/quake-terminal that might be interesting to you

**Comment by BANOnotIT** [comment]
Thanks a lot. By a coincidence, somebody showed me a link to gjs.guide also yesterday. Turns out AI stuff can generate pretty okay gjs code.

P.S.

Thanks, that's kinda what I was looking for something that'll replace guake terminal that I was using back in the day. But the problem with the project you linked is that it uses "switch to workspace with opened terminal" which I want to change here. I think make an issue there linking to this extension when we're done xD

**Comment by hedgieinsocks** [comment]
Gotcha! In the meantime, the gjs code is already done. So will push right after merging your PR.

**Comment by hedgieinsocks** [comment]
@BANOnotIT Thank you for your contribution! Please pull the latest master to test the implemented functionality

**Comment by BANOnotIT** [comment]
Tested several cases and 1 terminal instance (term) across several workspaces (WSs). This is the most common use case and it works great.

But if we do 2 term + 3 WSs the algorithm has kinda strange priority:
1. Checks instances in current workspace
2. Then checks latest opened window instances
3. If no instance above found, uses the youngest minimized instance

I suppose, that this is the result of how window queue is implemented in GNOME generally.  This doesn't affect the main use case, but I felt the urge to document this edge case behavior for future.

Other then that, not it fully solves my use case and I'm glad it worked out. Thank you!

**Comment by hedgieinsocks** [comment]
Good to hear it solved the main issue! As for the priority order in multi-instance-across-wms cases, which one would you expect?

**Comment by BANOnotIT** [comment]
I don't have any preference regarding priority, since I'll only use 1 terminal instance with tabs inside across all workspaces.

But I tested things with several instances and wrote down my findings.

Other than that, I thinks it's okay to go to the other extension and ask them if they can implement something similar

**Comment by BANOnotIT** [comment]
Well, the order is only relative if we're talking about "switch to the workspace" mode. For others, it doesn't really make much sense.

But for switching, I think recently focused order (similar to Super + Tab and Alt + \`) would be a better fit for existing habits.
